<?php

namespace AppBundle\Repository;

/**
 * albumsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class albumsRepository extends \Doctrine\ORM\EntityRepository
{
}
