<?php

namespace AppBundle\Repository;

/**
 * artistsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class artistsRepository extends \Doctrine\ORM\EntityRepository
{
}
